# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ecac77faa162e5c5226fc7a758b10d428ea46c11be94834b0f325430004f501e109c6a3dee4691721c592e49666ef5a4bd4b4857e352438bc4e15237dc5c60a

test:
  secret_key_base: eda1d9394afe2e71d5574820373441273484981c70944c5bca8c7f45fab23fc87e9f8af309f1a493ab2f14d22604a29858061d80ec680cf76cbd682044a50695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
